--- #YAML:1.0
name:                HTML-FormatText-WithLinks-AndTables
version:             0.01
abstract:            Converts HTML to Text with tables in tact
license:             ~
author:              
    - Shaun Fryer <pause.cpan.org@sourcery.ca>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    HTML::FormatText::WithLinks:   0
    HTML::TreeBuilder:             0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
